services: 
    db:
        container_name: postgres-db-multikart
        image: postgres
        restart: always
        ports:
          - "5432:5432"
        volumes:
          - ../pgdb:/var/lib/postgresql/data
        environment: 
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: user
          POSTGRES_DB: multikart

    adminer:
        image: adminer
        restart: always
        ports:
            - localhost 

    # redisdb:
    #     image: redis
    #     restart: always
    #     ports:
    #         - 6379:6379
 

    
