# Generated by Django 4.0.2 on 2022-03-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='surname')),
                ('email', models.EmailField(max_length=30, verbose_name='e-mail')),
                ('phone_number', models.IntegerField(verbose_name='mobile number')),
                ('message', models.TextField(help_text='Type your message here...', verbose_name='your message')),
            ],
        ),
    ]
