# Generated by Django 4.0.3 on 2022-04-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=30, unique=True, verbose_name='e-mail'),
        ),
    ]
