# Generated by Django 3.2.13 on 2022-06-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
