# Generated by Django 3.2.13 on 2022-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_propertyname_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
    ]
