# Generated by Django 4.0.3 on 2022-04-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Image title'),
        ),
    ]
