# Generated by Django 4.0.3 on 2022-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_description_az_product_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.AddField(
            model_name='category',
            name='title_az',
            field=models.CharField(max_length=70, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=70, null=True, verbose_name='title'),
        ),
    ]
