# Generated by Django 4.0.3 on 2022-04-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
    ]
