# Generated by Django 4.0.3 on 2022-04-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_review_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
    ]
