# Generated by Django 3.2.13 on 2022-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='price',
            field=models.IntegerField(max_length=50, verbose_name='Price'),
        ),
    ]
