# Generated by Django 4.0.3 on 2022-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brands_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='media/categories/')),
                ('is_main', models.BooleanField(default=False, verbose_name='verified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brands', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='praduct',
            options={'verbose_name': 'Praduct', 'verbose_name_plural': 'Praduct'},
        ),
    ]
