# Generated by Django 4.0.3 on 2022-05-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productversion_title_az_productversion_title_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
