# Generated by Django 3.2.13 on 2022-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productversion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
