# Generated by Django 4.0.3 on 2022-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
    ]
