# Generated by Django 4.0.3 on 2022-04-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='product.product'),
        ),
    ]
