# Generated by Django 3.2.13 on 2022-06-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productversion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='old_price',
            field=models.IntegerField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='discount_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_set', to='product.discount'),
        ),
    ]
