# Generated by Django 4.0.3 on 2022-03-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_images_alter_brands_options_alter_praduct_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
