# Generated by Django 4.0.3 on 2022-05-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_brand_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='title_en',
        ),
    ]
