# Generated by Django 3.2.13 on 2022-06-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220627_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='old_price',
            field=models.IntegerField(null=True, verbose_name='New-Price'),
        ),
    ]
