# Generated by Django 3.2.13 on 2022-05-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_description_az_product_description_en'),
        ('product', '0006_remove_category_title_az_remove_category_title_en_and_more'),
    ]

    operations = [
    ]
