# Generated by Django 4.0.3 on 2022-04-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_parent_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='parent',
        ),
    ]
