# Generated by Django 3.2.13 on 2022-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productversion_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='old_price',
            field=models.IntegerField(null=True, verbose_name='old-Price'),
        ),
    ]
