# Generated by Django 3.2.13 on 2022-07-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productversion_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='old_price',
        ),
    ]
