# Generated by Django 4.0.3 on 2022-04-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_parent_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'verbose_name': 'Property values', 'verbose_name_plural': 'Property values'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='parent_category',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/'),
        ),
        migrations.AlterField(
            model_name='propertyname',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_property_name', to='product.category'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='property_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_name_property_value', to='product.propertyname'),
        ),
    ]
