# Generated by Django 4.0.3 on 2022-04-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_propertyvalue_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent_id',
        ),
    ]
