# Generated by Django 3.2.13 on 2022-07-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='subject',
        ),
    ]
