# Generated by Django 3.2.13 on 2022-07-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_title_review_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='Subject'),
        ),
    ]
