# Generated by Django 3.2.13 on 2022-07-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
