# Generated by Django 3.2.13 on 2022-06-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='surname')),
                ('email', models.EmailField(max_length=30, verbose_name='e-mail')),
                ('phone_number', models.CharField(max_length=200, verbose_name='mobile number')),
                ('country', models.TextField(choices=[('1', 'India'), ('2', 'South Africa'), ('3', 'United States'), ('4', 'Australia')], verbose_name='Country')),
                ('city_town', models.CharField(help_text='City/Town', max_length=50, verbose_name='City/Town')),
                ('address', models.CharField(help_text='Street Address', max_length=150, verbose_name='Address')),
                ('state', models.CharField(max_length=50, verbose_name='State/Country')),
                ('postal_code', models.CharField(max_length=30, verbose_name='Postal Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='surname')),
                ('email', models.EmailField(max_length=50, verbose_name='e-mail')),
                ('phone_number', models.CharField(max_length=150, verbose_name='mobile number')),
                ('country', models.TextField(choices=[('1', 'India'), ('2', 'South Africa'), ('3', 'United States'), ('4', 'Australia')], verbose_name='Country')),
                ('city_town', models.CharField(help_text='City/Town', max_length=50, verbose_name='City/Town')),
                ('address', models.CharField(help_text='Street Address', max_length=150, verbose_name='Address')),
                ('state', models.CharField(max_length=50, verbose_name='State/Country')),
                ('postal_code', models.CharField(max_length=30, verbose_name='Postal Code')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.booking')),
                ('customer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_payment', models.FloatField(max_length=50, verbose_name='total payment for order')),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.basket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_set', to='order.booking')),
                ('product_version_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.productversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.customer'),
        ),
    ]
