# Generated by Django 4.0.3 on 2022-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='surname')),
                ('email', models.EmailField(max_length=30, verbose_name='e-mail')),
                ('phone_number', models.IntegerField(verbose_name='mobile number')),
                ('country', models.TextField(choices=[('1', 'India'), ('2', 'South Africa'), ('3', 'United States'), ('4', 'Australia')], verbose_name='Country')),
                ('address', models.CharField(help_text='Street Address', max_length=150, verbose_name='Address')),
                ('state', models.CharField(max_length=50, verbose_name='State/Country')),
                ('postal_code', models.IntegerField(verbose_name='Postal Code')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.IntegerField(verbose_name='basket id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
