# Generated by Django 4.0.3 on 2022-05-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetail',
            name='user_name',
        ),
    ]
