# Generated by Django 4.0.3 on 2022-03-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delete_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingDetails',
            new_name='BillingDetail',
        ),
    ]
