# Generated by Django 3.2.13 on 2022-06-23 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_review_title'),
        ('order', '0003_rename_customer_id_booking_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('product_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productversion')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='product_version_id',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
