# Generated by Django 4.0.3 on 2022-03-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
        ('order', '0003_rename_billingdetails_billingdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_payment', models.FloatField(max_length=50, verbose_name='total payment for order')),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.basket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
