# Generated by Django 4.0.3 on 2022-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='town_city',
            field=models.CharField(default='Mumbai', max_length=50, verbose_name='Town/City'),
        ),
    ]
