# Generated by Django 4.0.3 on 2022-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_billingdetail_town_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='create_account',
            field=models.BooleanField(default=False, verbose_name='Create an account?'),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='phone_number',
            field=models.TextField(verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='billingdetail',
            name='town_city',
            field=models.CharField(max_length=50, verbose_name='Town/City'),
        ),
    ]
