# Generated by Django 4.0.3 on 2022-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_billingdetail_create_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='mobile number'),
        ),
    ]
