# Generated by Django 4.0.3 on 2022-03-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
